import jsPDF from 'jspdf';

export function generatePDF(assessment) {
  const doc = new jsPDF();
  let y = 20;
  const pageHeight = 280;
  const margin = 20;

  const checkPageBreak = (needed = 10) => {
    if (y + needed > pageHeight) {
      doc.addPage();
      y = 20;
    }
  };

  const addTitle = (text) => {
    checkPageBreak(15);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text(text, margin, y);
    y += 8;
    doc.setDrawColor(200);
    doc.line(margin, y, 190, y);
    y += 5;
  };

  const addSubTitle = (text) => {
    checkPageBreak(10);
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text(text, margin, y);
    y += 6;
  };

  const addRow = (label, value) => {
    checkPageBreak(8);
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`${label}: ${value}`, margin + 5, y);
    y += 5;
  };

  // Header
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.text('PhysioCheck Assessment Report', margin, y);
  y += 10;
  doc.setFontSize(12);
  doc.setFont(undefined, 'normal');
  doc.text(`${assessment.specialtyName} Assessment`, margin, y);
  y += 6;
  doc.text(`Date: ${new Date(assessment.date).toLocaleDateString()}`, margin, y);
  y += 10;

  // Patient Info
  addTitle('Patient Information');
  const cf = assessment.commonFields || {};
  addRow('Name', cf.patientName || 'N/A');
  addRow('Age', cf.age || 'N/A');
  addRow('Gender', cf.gender || 'N/A');
  addRow('Diagnosis', cf.diagnosis || 'N/A');
  addRow('VAS', cf.vas != null ? `${cf.vas}/10` : 'N/A');
  addRow('NPRS', cf.nprs != null ? `${cf.nprs}/10` : 'N/A');
  y += 5;

  // Findings
  const filledFindings = Object.entries(assessment.findings || {}).filter(([, v]) => v && v !== false);
  if (filledFindings.length > 0) {
    addTitle('Assessment Findings');
    let currentSection = '';
    filledFindings.forEach(([key, value]) => {
      const parts = key.split('|');
      const section = parts[0];
      const label = parts[parts.length - 1];
      if (section !== currentSection) {
        currentSection = section;
        addSubTitle(section);
      }
      addRow(label, value === true ? 'Present' : value);
    });
    y += 5;
  }

  // Special Tests
  const filledTests = Object.entries(assessment.specialTestResults || {}).filter(([, v]) => v);
  if (filledTests.length > 0) {
    addTitle('Special Test Results');
    filledTests.forEach(([name, result]) => addRow(name, result));
    y += 5;
  }

  // Outcome Scores
  const filledScores = Object.entries(assessment.outcomeScores || {}).filter(([, v]) => v);
  if (filledScores.length > 0) {
    addTitle('Outcome Measure Scores');
    filledScores.forEach(([name, score]) => addRow(name, score));
    y += 5;
  }

  // Problem List
  if (assessment.problemList?.length > 0) {
    addTitle('Problem List');
    assessment.problemList.forEach((p, i) => {
      checkPageBreak(8);
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text(`${i + 1}. ${p}`, margin + 5, y);
      y += 5;
    });
    y += 5;
  }

  // Goals
  if (assessment.goals?.shortTerm?.length > 0 || assessment.goals?.longTerm?.length > 0) {
    addTitle('Treatment Goals');
    if (assessment.goals.shortTerm?.length > 0) {
      addSubTitle('Short-term Goals');
      assessment.goals.shortTerm.forEach(g => addRow('-', g));
    }
    if (assessment.goals.longTerm?.length > 0) {
      addSubTitle('Long-term Goals');
      assessment.goals.longTerm.forEach(g => addRow('-', g));
    }
    y += 5;
  }

  // Notes
  if (assessment.notes) {
    addTitle('Therapist Notes');
    checkPageBreak(15);
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    const lines = doc.splitTextToSize(assessment.notes, 170);
    lines.forEach(line => {
      checkPageBreak(6);
      doc.text(line, margin + 5, y);
      y += 5;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(`Generated by PhysioCheck | Page ${i} of ${pageCount}`, margin, 290);
  }

  const patientName = (cf.patientName || 'patient').replace(/\s+/g, '_');
  doc.save(`PhysioCheck_${patientName}_${assessment.specialtyName}_${new Date(assessment.date).toISOString().split('T')[0]}.pdf`);
}
